List<Map<String, dynamic>> ticketList = [
  {
    'from': {'code': "NYC", 'name': "New-York"},
    'to': {'code': "LDN", 'name': "London"},
    'flying_time': '8H 30M',
    'date': "1 MAY",
    'departure_time': "08:00 AM",
    "number": 23,
  },
  {
    'from': {'code': "DK", 'name': "Dhaka"},
    'to': {'code': "SH", 'name': "Shanghai"},
    'flying_time': '4H 20M',
    'date': "10 MAY",
    'departure_time': "09:00 AM",
    "number": 45,
  },
  {
    'from': {'code': "IQ", 'name': "iraq"},
    'to': {'code': "IR", 'name': "iran"},
    'flying_time': '2H 20M',
    'date': "22 AUG",
    'departure_time': "10:00 AM",
    "number": 25,
  },
  {
    'from': {'code': "Japan", 'name': "JP"},
    'to': {'code': "QA", 'name': "Qatar"},
    'flying_time': '7H 20M',
    'date': "1 SPT",
    'departure_time': "07:00 AM",
    "number": 13,
  },
  {
    'from': {'code': "Japan", 'name': "JP"},
    'to': {'code': "QA", 'name': "Qatar"},
    'flying_time': '7H 20M',
    'date': "1 SPT",
    'departure_time': "07:00 AM",
    "number": 13,
  },
];
